### ISSUE TITLE
NoSuchMethodError: SerialDescriptorsKt.getNonNullOriginal

### ISSUE THREAD

**Issue by ydavygora** [avro-kotlin/avro4k#281]
**Is your feature request related to a problem? Please describe.**
In the file https://github.com/avro-kotlin/avro4k/blob/a7b9a6c012965b150b7b34e77270a5f4456e3716/src/main/kotlin/com/github/avrokotlin/avro4k/internal/helpers.kt#L17, you import nonNullOriginal from kotlinx.serialization.descriptors. This has been removed from the most recent version of kotlinx-serialization. When trying to just print the schema of data class (we're using Kotlin 2.1.10), it fails with the error

```
'kotlinx.serialization.descriptors.SerialDescriptor kotlinx.serialization.descriptors.SerialDescriptorsKt.getNonNullOriginal(kotlinx.serialization.descriptors.SerialDescriptor)'
java.lang.NoSuchMethodError: 'kotlinx.serialization.descriptors.SerialDescriptor kotlinx.serialization.descriptors.SerialDescriptorsKt.getNonNullOriginal(kotlinx.serialization.descriptors.SerialDescriptor)'
```

**Describe the solution you'd like**
The recommendation for the newest Kotlin releases is to just use serialName directly on the descriptor instance. If you could provide a version which would be compatible with the recent Kotlin versions, that would be great.

**Describe alternatives you've considered**
I considered downgrading Kotlin to <=1.8.0, however ultimately I decided against it for two reasons:
1. I don't want to lose the optimization of the new K2 compiler
2. There are alternative Avro libraries for JVM which work with Kotlin 2.1

**Additional context**
No additional context

**Comment by Chuckame** [comment]
The most recent kotlinx-serialization still have it, and has been released in their 1.7.0-RC.

**Comment by Chuckame** [comment]
The most recent kotlinx-serialization still have it, and has been released in their 1.7.0-RC: https://github.com/Kotlin/kotlinx.serialization/blob/master/core/commonMain/src/kotlinx/serialization/descriptors/SerialDescriptors.kt#L252

Please ensure [the version matrix](https://github.com/avro-kotlin/avro4k?tab=readme-ov-file#versions-matrix) has been respected.

That said: ensure kotlinx-serialization in your classpath or your dependency tree is >=1.7.0

**Comment by ydavygora** [comment]
Hi @Chuckame ,

you're right. I was about to argue with you and create a minimal failing example, but it actually worked. Now I need to figure out why it didn't work in our project. Thank you very much and sorry for wasting your time!

Best,
Yuriy
